spring:
  application:
    name: hello-kur-service

server.port: 8072

eureka:
  client:
    registerWitEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost