spring:
  application:
    name: zuul-service

server:
  port: 8073

zuul:
  prefix: /api
  routes:
    hello-kur-server:
      path: /server/**
      serviceId: HELLO-KUR-SERVER
    hello-kur-service:
      path: /client/**
      serviceId: HELLO-KUR-SERVICE

eureka:
  client:
    registerWitEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# Increase the Hystrix timeout to 3s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000